### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by pjduplooy1** [Rasmus-M/js99er-angular#13]
Hiya

1.  Installed newest NodeJS
2.   Clone repository
3.   Installed both angular and http-server
4.   Did a npm install in src directory as always.
5.  In js99er-angular base folder I did ng build --prod.

Get the following error:

An unhandled exception occurred: error TS5083: Cannot read file 'C:/js99er-angular/tsconfig.base.json'.

See "C:\Users\pjdup\AppData\Local\Temp\ng-R0qoX3\angular-errors.log" for further details.

Contents of that logfile is:

[error] Error: [91merror[0m[90m TS5083: [0mCannot read file 'C:/js99er-angular/tsconfig.base.json'.

    at Object.readTsconfig (C:\js99er-angular\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\read-tsconfig.js:28:15)
    at Object.configureI18nBuild (C:\js99er-angular\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:98:38)
    at Object.generateI18nBrowserWebpackConfigFromContext (C:\js99er-angular\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:86:57)
    at buildBrowserWebpackConfigFromContext (C:\js99er-angular\node_modules\@angular-devkit\build-angular\src\browser\index.js:68:41)
    at initialize (C:\js99er-angular\node_modules\@angular-devkit\build-angular\src\browser\index.js:97:69)
    at buildWebpackBrowser (C:\js99er-angular\node_modules\@angular-devkit\build-angular\src\browser\index.js:115:24)
    at onInput (C:\js99er-angular\node_modules\@angular-devkit\architect\src\create-builder.js:151:30)
    at SafeSubscriber._next (C:\js99er-angular\node_modules\@angular-devkit\architect\src\create-builder.js:65:29)
    at SafeSubscriber.__tryOrUnsub (C:\js99er-angular\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\js99er-angular\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\js99er-angular\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\js99er-angular\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Object.next (C:\js99er-angular\node_modules\rxjs\internal\observable\onErrorResumeNext.js:22:49)
    at SafeSubscriber.__tryOrUnsub (C:\js99er-angular\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\js99er-angular\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\js99er-angular\node_modules\rxjs\internal\Subscriber.js:89:26)

Can you help please?

All on Windows

**Comment by Rasmus-M** [comment]
I don't know why the file was removed from git, but it's back now.
Rasmus
